x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  user-service:
    logging: *default-logging

  itinerary-service:
    logging: *default-logging

  destination-service:
    logging: *default-logging

  api-gateway:
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "--threads", "8", "--timeout", "60", "--access-logfile", "-", "app:app"]
    logging: *default-logging